version: '3.8'

services:
  sqlserver:
    build: .
    container_name: sqlserver2017
    environment:
      SA_PASSWORD: "SenhaThomas123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserverdata: